// CB Studios product metadata.
// Keep this file factual: do not add prices, ratings, download counts, or unsupported claims.

window.CB_PRODUCTS = [
  {
    slug: "heat-map",
    name: "CB Heatmap",
    resource: "cb_heatmap",
    platform: "FiveM",
    category: "Scripts",
    type: "paid",
    docPath: "/scripts/heat-map.md",
    storeUrl: "https://pichirin-cb.tebex.io/",
    githubUrl: null,
    discordUrl: null,
    frameworks: ["QBCore", "ESX", "Standalone"],
    status: "Stable",
    featured: false,
    description: "Privacy-first organic player activity heatmap for FiveM servers with anonymous activity sampling and persistent Discord publishing."
  },
  {
    slug: "tactical-notify",
    name: "Tactical Notify",
    resource: "cb_opsNotify",
    platform: "FiveM",
    category: "Scripts",
    type: "free",
    docPath: "/scripts/tactical-notify.md",
    storeUrl: "https://pichirin-cb.tebex.io/",
    githubUrl: null,
    discordUrl: null,
    frameworks: ["ESX", "QBCore", "Standalone"],
    status: "Stable",
    featured: true,
    description: "Lightweight notification and help-prompt system with NUI, sounds, exports, and compatibility hooks for common frameworks."
  },
  {
    slug: "apocalypse-extraction",
    name: "Apocalypse Extraction",
    resource: "cb_deadzone-extract",
    platform: "FiveM",
    category: "Scripts",
    type: "free",
    docPath: "/scripts/apocalypse-extraction.md",
    storeUrl: "https://pichirin-cb.tebex.io/",
    githubUrl: null,
    discordUrl: null,
    frameworks: ["ESX", "QB", "QBX", "Standalone"],
    status: "Stable",
    featured: true,
    description: "Helicopter extraction system for deadzone gameplay with route control, configurable costs, SQL logging, inventory adapters, and notifications."
  },
  {
    slug: "electric-cuba",
    name: "Cuban Electric Company",
    resource: "cb_electrica-cuba",
    platform: "FiveM",
    category: "Scripts",
    type: "paid",
    docPath: "/scripts/electric-cuba.md",
    storeUrl: "https://pichirin-cb.tebex.io/",
    githubUrl: null,
    discordUrl: null,
    frameworks: ["ESX", "QBCore", "Standalone"],
    status: "Stable",
    featured: true,
    description: "Electrical-grid gameplay system with circuits, blackouts, tanker logistics, persistent state, webhooks, and adapter-based framework support."
  },
  {
    slug: "cadeca-cuba",
    name: "CADECA Cuba Exchange",
    resource: "cb_cadeca-cuba",
    platform: "FiveM",
    category: "Scripts",
    type: "paid",
    docPath: "/scripts/cadeca-cuba.md",
    storeUrl: "https://pichirin-cb.tebex.io/",
    githubUrl: null,
    discordUrl: null,
    frameworks: ["ESX", "QBCore", "QBox", "Custom"],
    status: "Stable",
    featured: true,
    description: "Cuban-style exchange house script for USD and CUP conversion with configurable rates, NPC interaction, anti-abuse controls, and webhooks."
  },

  {
    slug: "swat-vehicle-pack",
    name: "SWAT Vehicle Pack",
    resource: "cb_truck-swat",
    platform: "FiveM",
    category: "Vehicle Packs",
    type: "paid",
    docPath: "/vehicles/swat-vehicle-pack.md",
    storeUrl: null,
    githubUrl: null,
    discordUrl: "https://discord.gg/hsx6AvBg5s",
    frameworks: [],
    status: "Stable",
    featured: false,
    description: "Special operations vehicle pack for FiveM servers, documented with installation, handling, streaming, and support guidance."
  },
  {
    slug: "truck-vehicle-pack",
    name: "Truck Vehicle Pack",
    resource: "cb_pack-truck",
    platform: "FiveM",
    category: "Vehicle Packs",
    type: "paid",
    docPath: "/vehicles/truck-vehicle-pack.md",
    storeUrl: null,
    githubUrl: null,
    discordUrl: "https://discord.gg/hsx6AvBg5s",
    frameworks: ["ESX", "QBCore", "QBox", "Standalone"],
    status: "Stable",
    featured: false,
    description: "Truck-focused FiveM vehicle pack with documented installation, streaming structure, handling notes, and troubleshooting guidance."
  },
  {
    slug: "car-sound-pack",
    name: "Car Sound Pack",
    resource: "cb_sonidos-vehiculos",
    platform: "FiveM",
    category: "Audio Packs",
    type: "paid",
    docPath: "/audio/car-sound-pack.md",
    storeUrl: null,
    githubUrl: null,
    discordUrl: "https://discord.gg/hsx6AvBg5s",
    frameworks: [],
    status: "Stable",
    featured: false,
    description: "Vehicle sound pack for FiveM, modified and adapted by CB Studios with documented installation and testing steps."
  },
  {
    slug: "industrial-truck-workshop",
    name: "Industrial Truck Workshop",
    resource: "cb_workshop-truck",
    platform: "FiveM",
    category: "MLO / Mapping",
    type: "paid",
    docPath: "/mlo-mapping/industrial-truck-workshop.md",
    storeUrl: null,
    githubUrl: null,
    discordUrl: "https://discord.gg/hsx6AvBg5s",
    frameworks: [],
    status: "Stable",
    featured: false,
    description: "Truck workshop interior and mapping resource for FiveM servers, focused on industrial roleplay environments."
  },

  {
    slug: "fortuna-hunting-wagon",
    name: "Fortuna Hunting Wagon",
    resource: "fortuna_huntingwagon",
    platform: "RedM",
    category: "Scripts",
    type: "free",
    docPath: "/scripts/fortuna-hunting-wagon.md",
    storeUrl: null,
    githubUrl: "https://github.com/Pichirin-CB/fortuna_huntingwagon",
    discordUrl: null,
    frameworks: ["Standalone", "VORP"],
    status: "Stable",
    featured: false,
    description: "Secure RedM hunting-wagon cargo system with validated storage, configurable capacity, localization, and optional VORP integration."
  },
  {
    slug: "fortuna-hunting-zones",
    name: "Fortuna Hunting Zones",
    resource: "fortuna_huntingzones",
    platform: "RedM",
    category: "Scripts",
    type: "free",
    docPath: "/scripts/fortuna-hunting-zones.md",
    storeUrl: null,
    githubUrl: "https://github.com/Pichirin-CB/fortuna_huntingzones",
    discordUrl: null,
    frameworks: ["VORP"],
    status: "Stable",
    featured: false,
    description: "Collaborative RedM hunting heatmap with proximity-based observations, persistent filters, localization, and VORP integration."
  }
];

